name: carbon_emission_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.2.1
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
